### ISSUE TITLE
Cleaner code

### ISSUE THREAD

**Issue by OutThisLife** [melnik909/css-helpers#1]
![image](https://user-images.githubusercontent.com/770929/77353510-1a377300-6d0f-11ea-9ae3-508179f1870e.png)

- Unnecessary line break at the top of every document
- Using `!important` is lazy, bad practice: https://stackoverflow.com/a/3706876
- Need to choose between tabs or spaces, preferably enforced by `prettier`

And in my opinion, there should be a space after opening brackets.

ref: https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882

**Comment by melnik909** [comment]
- Unnecessary line break at the top of every document
- Need to choose between tabs or spaces, preferably enforced by prettier

The code is writtenaccording to my preferences

- Using !important is lazy, bad practice
I recommend to learn why the !important is a bad practice. Then you can understand that I don't use it as a bad practice.
